### ISSUE TITLE
Extend committee yaml to remove redundancy

### ISSUE THREAD

**Issue by AlexJBanks** [CSSUoB/cssuob.github.io#235]
Extend yaml structure to define one person who has done multiple roles in one year, or multiple roles across multiple years, removing redundancy

**Comment by LikkanChung** [comment]
This will likely need to involve a refactor of how the committee list is generated from a group-first approach to a person-first approach. 

Currently each committee group is listed separately with a person appearing in multiple lists of committees. A possible solution would be to change it to a list of people who have multiple roles. 

e.g. 
``` yaml
committee-members: 
  - name: person1
    pronouns: they/them
    ...
    roles: 
      - role1
        ...
      - role2
  - name: person2
    ...
```
